<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_react_tab_selected</name>
   <tag></tag>
   <elementGuidId>838c06fb-6ebc-46ab-8c3f-ffd253fbe284</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//ul[@role='tablist']//li[@aria-selected='true']//div[text()='${tabName}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//ul[@role='tablist']//li[@aria-selected='true']//div[text()='${tabName}']</value>
   </webElementProperties>
</WebElementEntity>
