<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_to_date_picker</name>
   <tag></tag>
   <elementGuidId>19ef7ee9-c09d-46dd-8f35-5c18440a2210</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[text()='To']/parent::div[@class='to']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[text()='To']/parent::div[@class='to']/span</value>
   </webElementProperties>
</WebElementEntity>
