<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_from_date_picker</name>
   <tag></tag>
   <elementGuidId>b4b63ab4-5e12-4444-ba06-f58d70ad183a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[text()='From']/parent::div[@class='from']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[text()='From']/parent::div[@class='from']/span</value>
   </webElementProperties>
</WebElementEntity>
