<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_react_tabs</name>
   <tag></tag>
   <elementGuidId>5221a95d-93ce-4f3c-9756-8335503fa05d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//ul[@role='tablist']//div[text()='${tabName}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//ul[@role='tablist']//div[text()='${tabName}']</value>
   </webElementProperties>
</WebElementEntity>
