<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_submit_data</name>
   <tag></tag>
   <elementGuidId>f9a6aaea-a83c-4fcd-bfef-79c227b40b5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='modal-inner-container']//button/div[text()='Submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='modal-inner-container']//button/div[text()='Submit']</value>
   </webElementProperties>
</WebElementEntity>
