<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_apply_date_filter</name>
   <tag></tag>
   <elementGuidId>53d6f821-527e-444d-aec5-af76288ad49e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button/div[text()='Apply']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button/div[text()='Apply']</value>
   </webElementProperties>
</WebElementEntity>
