<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_model_type</name>
   <tag></tag>
   <elementGuidId>1a400b3a-5958-439d-bbfe-daa12cad2dad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//li[@role='tab']/div[text()='${modelType}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//li[@role='tab']/div[text()='${modelType}']</value>
   </webElementProperties>
</WebElementEntity>
