<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_date_filter</name>
   <tag></tag>
   <elementGuidId>56319c60-92fa-4250-909c-b742615a6b6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[text()='${filterName}']/parent::label//input[@type='radio']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[text()='${filterName}']/parent::label//input[@type='radio']</value>
   </webElementProperties>
</WebElementEntity>
