<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_model_text_area</name>
   <tag></tag>
   <elementGuidId>89dedbca-012c-421b-8d1f-4b5224420724</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//textarea[@name='model']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name='model']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//textarea[@name='model']</value>
   </webElementProperties>
</WebElementEntity>
