<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_sidebar_item_highlighted</name>
   <tag></tag>
   <elementGuidId>e7e805aa-3220-436f-8401-6451e9b23847</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='sidebar']//div[contains(@class,'highlight')]/div[text()='${name}']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='sidebar']//div[contains(@class,'highlight')]/div[text()='${name}']</value>
   </webElementProperties>
</WebElementEntity>
